# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'



target 'NeCTARClient' do
    pod 'Alamofire', '~>3.4'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'PromiseKit', '~> 3.0.3'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SnapKit', '~> 0.19.1'
    pod 'SwiftDate', '~> 3.0.8'
    pod 'IBAnimatable', git: 'https://github.com/JakeLin/IBAnimatable.git'
    pod 'Charts'
#    pod 'SQLite.swift', '~> 0.9.2'
#    pod 'SDWebImage', '~>3.7'
#    pod 'CocoaLumberjack/Swift'
#    pod 'Fabric'
    pod 'YXJKxMenu'
#    pod 'iCheckbox'
    pod 'TNSwiftyCheckboxGroup'
    pod 'RAMAnimatedTabBarController', "~> 1.5.3"
end
